version: '3.1'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: session
  postgres:
    image: "postgres:latest"
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=cameron77'
      - 'POSTGRES_USER=cameron'
    ports:
      - '5432:5432'
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "camestreete@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "cameron77"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
