/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as HomeLayoutImport } from './routes/_home/_layout'
import { Route as AuthenticatedLayoutImport } from './routes/_authenticated/_layout'
import { Route as HomeLayoutIndexImport } from './routes/_home/_layout/index'
import { Route as HomeLayoutAuthImport } from './routes/_home/_layout/auth'
import { Route as AuthenticatedLayoutDashboardIndexImport } from './routes/_authenticated/_layout/dashboard/index'
import { Route as AuthenticatedLayoutDashboardDocumentsIdIndexImport } from './routes/_authenticated/_layout/dashboard/$documentsId/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_home/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAuthRoute = HomeLayoutAuthImport.update({
  path: '/auth',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const AuthenticatedLayoutDashboardIndexRoute =
  AuthenticatedLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutDashboardDocumentsIdIndexRoute =
  AuthenticatedLayoutDashboardDocumentsIdIndexImport.update({
    path: '/dashboard/$documentsId/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout': {
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_home/_layout': {
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_home/_layout/auth': {
      preLoaderRoute: typeof HomeLayoutAuthImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_home/_layout/': {
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_authenticated/_layout/dashboard/': {
      preLoaderRoute: typeof AuthenticatedLayoutDashboardIndexImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/dashboard/$documentsId/': {
      preLoaderRoute: typeof AuthenticatedLayoutDashboardDocumentsIdIndexImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedLayoutRoute.addChildren([
      AuthenticatedLayoutDashboardIndexRoute,
      AuthenticatedLayoutDashboardDocumentsIdIndexRoute,
    ]),
  ]),
  HomeLayoutRoute.addChildren([HomeLayoutAuthRoute, HomeLayoutIndexRoute]),
])

/* prettier-ignore-end */
